# Generated by Django 3.2.7 on 2021-11-13 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solve', '0002_auto_20210906_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 13, 15, 45, 55, 71925)),
        ),
    ]
