# Generated by Django 3.2.7 on 2021-11-14 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solve', '0005_auto_20211114_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 15, 0, 24, 465746)),
        ),
    ]
